-- Reliability improvements for order intake.
-- Safe for existing installations: backfills a key for old rows before enforcing NOT NULL.

alter table public.orders
  add column if not exists client_order_id uuid;

update public.orders
set client_order_id = gen_random_uuid()
where client_order_id is null;

alter table public.orders
  alter column client_order_id set default gen_random_uuid(),
  alter column client_order_id set not null;

create unique index if not exists orders_client_order_id_key
  on public.orders (client_order_id);

create index if not exists orders_status_created_at_idx
  on public.orders (status, created_at desc);

alter table public.orders
  drop constraint if exists orders_delivery_type_check;

alter table public.orders
  add constraint orders_delivery_type_check
  check (delivery_type in ('delivery', 'retiro'));

alter table public.orders
  drop constraint if exists orders_delivery_fields_check;

alter table public.orders
  add constraint orders_delivery_fields_check
  check (
    (delivery_type = 'delivery' and address is not null and length(trim(address)) >= 4 and zone is not null)
    or
    (delivery_type = 'retiro' and address is null and zone is null)
  );

alter table public.orders
  drop constraint if exists orders_items_shape_check;

alter table public.orders
  add constraint orders_items_shape_check
  check (jsonb_typeof(items) = 'array' and jsonb_array_length(items) between 1 and 50);

-- The client key is intentionally accepted from anonymous customers so a network
-- retry can safely identify the already-created order through the unique index.
comment on column public.orders.client_order_id is
  'Stable UUID generated by the client to make retries and double clicks idempotent.';
